apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qnet-catalog-data
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: qnet-capstone
    app.kubernetes.io/part-of: qnet-data-quality
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
