apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qnet-ingest
  labels:
    app.kubernetes.io/name: ingest
    app.kubernetes.io/instance: qnet-capstone
    app.kubernetes.io/part-of: qnet-data-quality
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qnet-ingest
  minReplicas: 1
  maxReplicas: 4
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
