apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pipeline-backend-isolation
  namespace: data-platform
  labels:
    app: ai-data-pipeline
    lab: "4.3"
  annotations:
    lab.muoilt.vn/ingress: "allow only Lab 4.1 frontend Pods on TCP 8080"
    lab.muoilt.vn/egress: "deny 0.0.0.0/0 except kube-system DNS"
spec:
  podSelector:
    matchLabels:
      app: ai-data-pipeline
      lab: "4.1"
      component: normalizer-backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ai-data-pipeline
              lab: "4.1"
              component: frontend
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
