apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

labels:
  - pairs:
      environment: prod
    includeSelectors: true

images:
  - name: mualanhlung017/ai-data-pipeline
    newTag: 1.0.2

replicas:
  - name: pipeline-kustomize-auditor
    count: 3
