apiVersion: v1
kind: LimitRange
metadata:
  name: qnet-container-limits
  labels:
    app.kubernetes.io/part-of: qnet-data-quality
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 32Mi
      default:
        cpu: 250m
        memory: 256Mi
      min:
        cpu: 5m
        memory: 8Mi
      max:
        cpu: "1"
        memory: 512Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: qnet-project-quota
  labels:
    app.kubernetes.io/part-of: qnet-data-quality
spec:
  hard:
    pods: "25"
    services: "15"
    services.nodeports: "2"
    configmaps: "20"
    secrets: "10"
    persistentvolumeclaims: "3"
    requests.storage: 5Gi
    requests.cpu: "3"
    requests.memory: 3Gi
    limits.cpu: "8"
    limits.memory: 6Gi
